### PR TITLE
Merge tools repo

### PR DESCRIPTION
**Pull request by rfuzzo**
# Pull request template

Merge cp77tools repo from: https://github.com/WolvenKit/CP77Tools

### CODE REVIEW

**Comment by Traderain** [comment]
image
image
image
image

**Comment by Traderain** [comment]
In the future please target the dev branch when making a pr <3

**Comment by rfuzzo** [comment]
> 
> 
> In the future please target the dev branch when making a pr <3

okay! can we retarget?

**Comment by Traderain** [comment]
> > In the future please target the dev branch when making a pr <3
> 
> okay! can we retarget?

Did it for you already :)

**Pull request merged**
